import CartItem from './CartItem';
import Cart from './Cart';
import Navbar from './Navbar';
import React from 'react';
import firebase from 'firebase/compat/app';
import 'firebase/compat/auth';
import 'firebase/compat/firestore';

class App extends React.Component {
  constructor() {
    super();
    this.state = {
      product: [],  // simple plain js objecdt
      loading:true,

    }
    //thisincreaseQuantity=this.increaseQuantity.bind(this)
  }

  componentDidMount(){
  //  firebase
  //  .firestore()
  //   .collection('product')
  //   .get()
  //   .then((snapshot)=>{
  //  // console.log(snapshot);
  //     snapshot.docs.map((doc)=>{
  //      // console.log(doc.data());
  //     });
  //     const product=snapshot.docs.map((doc)=>{
  //       const data =doc.data();
  //       data['id']=doc.id; // we have made this id key in our data returned from firebase and its value is doc.id (generated by firebase)
  //       return data;
  //     //  return doc.data();
  //     })
  //     this.setState({
  //       product:product,
  //       loading:false
  //     })
  //   })

  firebase
   .firestore()
    .collection('product')
    .onSnapshot((snapshot)=>{
      // console.log(snapshot);
        //  snapshot.docs.map((doc)=>{
        //   // console.log(doc.data());
        //  });
         const product=snapshot.docs.map((doc)=>{
           const data =doc.data();
           data['id']=doc.id; // we have made this id key in our data returned from firebase and its value is doc.id (generated by firebase)
           return data;
         //  return doc.data();
         })
         this.setState({
           product:product,
           loading:false
         })
       })
   
  }



  handleIncrease = (item) => {
    const { product } = this.state;   //upar jis name se array bnaya hai woh aur ye name must be same
    const index = product.indexOf(item);

    //console.log(products);
    product[index].qty += 1;
    //console.log(product[index]);

    this.setState({
      product: product
    })

  }

  handleDecrease = (item1) => {
    const { product } = this.state;
    //console.log(item1);
    const index = product.indexOf(item1);
    if (product[index].qty == 0) {
      product[index].qty = 0
    } else {
      product[index].qty -= 1;
    }

    this.setState({
      product: product
    })
  }

  handleDelete = (id) => {
    const { product } = this.state;
    const item = product.filter((item) => item.id !== id)
    this.setState({
      product: item
    })

  }

  getCartCount = () => {
    const { product } = this.state;
    let count = 0;
    product.forEach((product) => {
      count += product.qty;
    })
    return count;
  }

  getTotal = () => {
    const { product } = this.state;
    let total = 0;
    product.forEach((product) => {
      total += product.qty * product.price;
    })
    return total;
  }
  render() {
    const { product,loading } = this.state;
    return (
      <div className="App">
        <Navbar count={this.getCartCount()} />
        <h1> Shopping Cart</h1>
        <Cart
          product={product}
          increaseQuantity={this.handleIncrease}
          decreaseQuantity={this.handleDecrease}
          deleteProduct={this.handleDelete} />
          {loading && <h1>Loading Products.....</h1>}    {/*this is conditional rendering i.e.if loading is true then heading will be shown.In react the element present after && will be shown on the screen*/}
        <div style={styles.total}>Total: {this.getTotal()}</div>
      </div>
    );
  }
}

const styles = {
  total: {
    fontSize: 22,
    fontWeight: 500,
    textAlign: "end",
    backgroundColor: "rgb(66, 103, 178)",
    paddingRight: 20,

  }
}

export default App;
